apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: finbot-http-redirect
  namespace: finbot
  labels:
    app.kubernetes.io/name: finbot
    app.kubernetes.io/part-of: finbot
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: mnnu-gateway
      namespace: gateway-system
      sectionName: http
  hostnames:
    - finbot.mnnu.eu.org
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: finbot
  namespace: finbot
  labels:
    app.kubernetes.io/name: finbot
    app.kubernetes.io/part-of: finbot
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: mnnu-gateway
      namespace: gateway-system
      sectionName: https
  hostnames:
    - finbot.mnnu.eu.org
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/v1/stream/
      timeouts:
        request: 0s
        backendRequest: 0s
      backendRefs:
        - group: ""
          kind: Service
          name: finbot-web
          port: 8780
          weight: 1
    - matches:
        - path:
            type: PathPrefix
            value: /api/v1/instant-research/
      timeouts:
        request: 0s
        backendRequest: 0s
      backendRefs:
        - group: ""
          kind: Service
          name: finbot-web
          port: 8780
          weight: 1
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: finbot-web
          port: 8780
          weight: 1
