import AddIcon from '@mui/icons-material/Add';
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutline';
import PlayArrowIcon from '@mui/icons-material/PlayArrow';
import SaveIcon from '@mui/icons-material/Save';
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import { useEffect, useMemo, useState } from 'react';

import { api } from './api';
import type { AgentRole, AiExperiment, AiModel, AiProvider, ReasoningEffort, SetupProfileDefinition, SetupProfilePreview, WorkflowDefinitionSummary, WorkflowVersion } from './types';
import { ErrorBlock, SectionTitle, formatTime, statusColor, statusLabel } from './ui';

export function SetupProfilesPanel({ profiles, onApplied }: { profiles: SetupProfileDefinition[]; onApplied: () => Promise<void> }) {
  const [preview, setPreview] = useState<SetupProfilePreview | null>(null);
  const [error, setError] = useState<unknown>(null);
  const [message, setMessage] = useState('');
  const [busy, setBusy] = useState(false);
  const choose = async (profile: SetupProfileDefinition) => { setError(null); try { setPreview(await api.previewSetupProfile(profile.profileId)); } catch (cause) { setError(cause); } };
  const apply = async () => { if (!preview) return; setBusy(true); setError(null); setMessage(''); try { const result = await api.applySetupProfile(preview.profile.profileId, crypto.randomUUID()); setMessage(`已应用 ${result.appliedKeys.length} 项，保留 ${result.preservedKeys.length} 项`); await onApplied(); setPreview(await api.previewSetupProfile(preview.profile.profileId)); } catch (cause) { setError(cause); } finally { setBusy(false); } };
  return <Stack spacing={2}>{error !== null && <ErrorBlock error={error} />}{message && <Alert severity="success">{message}</Alert>}<Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', lg: 'repeat(3, minmax(0, 1fr))' }, gap: 1.25 }}>{profiles.map((profile) => <Paper key={profile.profileId} variant="outlined" sx={{ p: 2 }}><Typography fontWeight={800}>{profile.displayName}</Typography><Typography variant="body2" color="text.secondary" sx={{ minHeight: { lg: 42 }, my: 1 }}>{profile.description}</Typography><Button size="small" onClick={() => void choose(profile)}>查看变更</Button></Paper>)}</Box>{preview && <Paper variant="outlined" sx={{ p: 2 }}><SectionTitle title={`${preview.profile.displayName} · 变更预览`} /><Stack spacing={.75}>{preview.changes.map((change) => <Stack key={change.key} direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" spacing={1}><Typography variant="body2" fontWeight={700}>{change.key}</Typography><Typography variant="body2" color="text.secondary">{change.currentValue} → {change.proposedValue}</Typography></Stack>)}{preview.changes.length === 0 && <Typography color="text.secondary">默认值已符合该档案。</Typography>}<Typography variant="caption" color="text.secondary">保留用户值：{preview.preservedKeys.join('、') || '无'} · 缺失字段：{preview.missingKeys.join('、') || '无'}</Typography><Button variant="contained" disabled={busy} onClick={() => void apply()} sx={{ alignSelf: 'flex-end' }}>应用未自定义项</Button></Stack></Paper>}</Stack>;
}

export function AgentRolesPanel({ roles, providers, models, onChanged }: { roles: AgentRole[]; providers: AiProvider[]; models: AiModel[]; onChanged: () => Promise<void> }) {
  const [editing, setEditing] = useState<AgentRole | null>(null);
  const [creating, setCreating] = useState(false);
  const [error, setError] = useState<unknown>(null);
  const remove = async (role: AgentRole) => { try { await api.deleteAgentRole(role.roleTemplateId, role.version); await onChanged(); } catch (cause) { setError(cause); } };
  return <Stack spacing={1.25}>{error !== null && <ErrorBlock error={error} />}<SectionTitle title="角色提示词库" action={<Button startIcon={<AddIcon />} onClick={() => setCreating(true)}>新建角色</Button>} />{roles.map((role) => <Paper key={role.roleTemplateId} variant="outlined" sx={{ p: 2 }}><Stack direction={{ xs: 'column', md: 'row' }} spacing={1.5} justifyContent="space-between"><Box><Stack direction="row" spacing={1}><Typography fontWeight={800}>{role.displayName}</Typography>{role.builtIn && <Chip size="small" label="内置" />}</Stack><Typography variant="body2" color="text.secondary">{role.objective}</Typography><Typography variant="caption" color="text.secondary">{role.defaultProviderProfileId} · {role.defaultModelName} · {role.defaultReasoningEffort}</Typography></Box><Stack direction="row" spacing={1}><Button size="small" onClick={() => setEditing(role)} disabled={role.builtIn}>编辑</Button><Button size="small" color="error" startIcon={<DeleteOutlineIcon />} onClick={() => void remove(role)} disabled={role.builtIn}>删除</Button></Stack></Stack></Paper>)}<RoleDialog key={editing?.roleTemplateId || (creating ? 'new' : 'closed')} open={creating || editing !== null} role={editing} providers={providers} models={models} close={() => { setCreating(false); setEditing(null); }} saved={async () => { setCreating(false); setEditing(null); await onChanged(); }} /></Stack>;
}

function RoleDialog({ open, role, providers, models, close, saved }: { open: boolean; role: AgentRole | null; providers: AiProvider[]; models: AiModel[]; close: () => void; saved: () => Promise<void> }) {
  const defaultModel = models.find((item) => item.enabled) || models[0];
  const [error, setError] = useState<unknown>(null);
  const [value, setValue] = useState(() => roleValue(role, defaultModel));
  const submit = async () => { setError(null); try { const body = { ...value, expectedVersion: role?.version ?? null }; if (role) await api.updateAgentRole(role.roleTemplateId, body); else await api.createAgentRole(body); await saved(); } catch (cause) { setError(cause); } };
  return <Dialog open={open} onClose={close} maxWidth="md" fullWidth><DialogTitle>{role ? '编辑角色' : '新建角色'}</DialogTitle><DialogContent dividers><Stack spacing={1.5}>{error !== null && <ErrorBlock error={error} />}<TextField label="角色名称" value={value.displayName} onChange={(event) => setValue({ ...value, displayName: event.target.value })} /><TextField label="角色目标" value={value.objective} onChange={(event) => setValue({ ...value, objective: event.target.value })} /><Stack direction={{ xs: 'column', md: 'row' }} spacing={1.5}><TextField select label="默认厂商" value={value.defaultProviderProfileId} onChange={(event) => { const model = models.find((item) => item.providerProfileId === event.target.value); setValue({ ...value, defaultProviderProfileId: event.target.value, defaultModelName: model?.modelName || value.defaultModelName }); }} fullWidth>{providers.map((provider) => <MenuItem key={provider.profileId} value={provider.profileId}>{provider.displayName}</MenuItem>)}</TextField><TextField select label="默认模型" value={value.defaultModelName} onChange={(event) => setValue({ ...value, defaultModelName: event.target.value })} fullWidth>{models.filter((model) => model.providerProfileId === value.defaultProviderProfileId).map((model) => <MenuItem key={model.modelProfileId} value={model.modelName}>{model.modelName}</MenuItem>)}</TextField><TextField select label="思考强度" value={value.defaultReasoningEffort} onChange={(event) => setValue({ ...value, defaultReasoningEffort: event.target.value as ReasoningEffort })} fullWidth>{['PROVIDER_DEFAULT', 'NONE', 'MINIMAL', 'LOW', 'MEDIUM', 'HIGH', 'XHIGH', 'MAX'].map((effort) => <MenuItem key={effort} value={effort}>{effort}</MenuItem>)}</TextField></Stack><TextField select label="输出契约" value={value.outputContract} onChange={(event) => setValue({ ...value, outputContract: event.target.value })}><MenuItem value="TEXT">文本</MenuItem><MenuItem value="RESEARCH_FINDINGS">研究发现</MenuItem><MenuItem value="DEBATE_ARGUMENT">辩论论点</MenuItem><MenuItem value="RISK_ASSESSMENT">风险评估</MenuItem><MenuItem value="CHAIR_VERDICT">主席裁决</MenuItem><MenuItem value="TRADE_DECISIONS">交易决策</MenuItem><MenuItem value="EXECUTION_VERDICT">执行复核</MenuItem></TextField><TextField multiline minRows={6} label="系统提示词" value={value.systemPrompt} onChange={(event) => setValue({ ...value, systemPrompt: event.target.value })} /><TextField multiline minRows={4} label="用户提示模板" value={value.userPromptTemplate} onChange={(event) => setValue({ ...value, userPromptTemplate: event.target.value })} /></Stack></DialogContent><DialogActions><Button onClick={close}>取消</Button><Button variant="contained" startIcon={<SaveIcon />} onClick={() => void submit()}>保存</Button></DialogActions></Dialog>;
}

function roleValue(role: AgentRole | null, model: AiModel | undefined) { return { displayName: role?.displayName || '自定义分析师', objective: role?.objective || '从指定视角审查证据、挑战共识并给出可验证结论', systemPrompt: role?.systemPrompt || '你是独立市场研究角色。只输出可审计的分析摘要，不输出隐藏思维链。', userPromptTemplate: role?.userPromptTemplate || '结合上游证据与其他角色观点，给出结论、反例、风险与置信度。', outputContract: role?.outputContract || 'DEBATE_ARGUMENT', defaultProviderProfileId: role?.defaultProviderProfileId || model?.providerProfileId || '', defaultModelName: role?.defaultModelName || model?.modelName || '', defaultReasoningEffort: role?.defaultReasoningEffort || model?.defaultReasoningEffort || 'HIGH' as ReasoningEffort }; }

export function AiExperimentsPanel({ experiments, definitions, onChanged }: { experiments: AiExperiment[]; definitions: WorkflowDefinitionSummary[]; onChanged: () => Promise<void> }) {
  const [workflowVersions, setWorkflowVersions] = useState<WorkflowVersion[]>([]);
  const [name, setName] = useState('工作流候选对比');
  const [control, setControl] = useState('');
  const [candidate, setCandidate] = useState('');
  const [error, setError] = useState<unknown>(null);
  useEffect(() => {
    let active = true;
    Promise.all(definitions.map((definition) => api.workflowVersions(definition.definitionId)))
      .then((values) => { if (active) setWorkflowVersions(values.flat()); })
      .catch((cause) => { if (active) setError(cause); });
    return () => { active = false; };
  }, [definitions]);
  const controlOptions = useMemo(() => workflowVersions.filter((version) => version.status === 'PUBLISHED'), [workflowVersions]);
  const controlVersion = workflowVersions.find((version) => version.versionId === control);
  const candidateOptions = useMemo(() => workflowVersions.filter((version) => version.status !== 'DRAFT' && version.definitionId === controlVersion?.definitionId && version.versionId !== control), [control, controlVersion?.definitionId, workflowVersions]);
  useEffect(() => {
    if (!control && controlOptions[0]) setControl(controlOptions[0].versionId);
  }, [control, controlOptions]);
  useEffect(() => {
    if (!candidateOptions.some((version) => version.versionId === candidate)) setCandidate(candidateOptions[0]?.versionId || '');
  }, [candidate, candidateOptions]);
  const versionLabel = (version: WorkflowVersion) => `${definitions.find((definition) => definition.definitionId === version.definitionId)?.name || version.definitionId} · v${version.versionNumber} · ${statusLabel(version.status)}`;
  const create = async () => { setError(null); try { await api.createAiExperiment({ displayName: name, status: 'DRAFT', controlWorkflowVersionId: control, candidateWorkflowVersionId: candidate, candidateAllocationBasisPoints: 5000, evaluationMetric: 'RESEARCH_EFFECTIVENESS', minimumSampleSize: 20, expectedVersion: null }); await onChanged(); } catch (cause) { setError(cause); } };
  const transition = async (experiment: AiExperiment, status: AiExperiment['status']) => { setError(null); try { await api.updateAiExperiment(experiment.experimentId, { displayName: experiment.displayName, status, controlWorkflowVersionId: experiment.controlWorkflowVersionId, candidateWorkflowVersionId: experiment.candidateWorkflowVersionId, candidateAllocationBasisPoints: experiment.candidateAllocationBasisPoints, evaluationMetric: experiment.evaluationMetric, minimumSampleSize: experiment.minimumSampleSize, expectedVersion: experiment.version }); await onChanged(); } catch (cause) { setError(cause); } };
  return <Stack spacing={1.5}>{error !== null && <ErrorBlock error={error} />}<Paper variant="outlined" sx={{ p: 2 }}><Stack direction={{ xs: 'column', lg: 'row' }} spacing={1.25}><TextField label="实验名称" value={name} onChange={(event) => setName(event.target.value)} fullWidth /><TextField select label="当前对照版本" value={control} onChange={(event) => setControl(event.target.value)} fullWidth>{controlOptions.map((version) => <MenuItem key={version.versionId} value={version.versionId}>{versionLabel(version)}</MenuItem>)}</TextField><TextField select label="历史候选版本" value={candidate} onChange={(event) => setCandidate(event.target.value)} fullWidth>{candidateOptions.map((version) => <MenuItem key={version.versionId} value={version.versionId}>{versionLabel(version)}</MenuItem>)}</TextField><Button variant="contained" startIcon={<AddIcon />} disabled={!control || !candidate || control === candidate} onClick={() => void create()}>创建</Button></Stack><Typography variant="caption" color="text.secondary" display="block" sx={{ mt: 1 }}>运行中实验按请求幂等键稳定分流；直接指定版本的即时研究不会被实验覆盖。</Typography></Paper>{experiments.map((experiment) => <Paper key={experiment.experimentId} variant="outlined" sx={{ p: 2 }}><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" spacing={1.5}><Box><Stack direction="row" spacing={1}><Typography fontWeight={800}>{experiment.displayName}</Typography><Chip size="small" color={statusColor(experiment.status)} label={statusLabel(experiment.status)} /></Stack><Typography variant="body2" color="text.secondary">对照 {experiment.controlWorkflowVersionId}（{experiment.controlSampleCount}） · 候选 {experiment.candidateWorkflowVersionId}（{experiment.candidateSampleCount}）</Typography><Typography variant="caption" color="text.secondary">候选流量 {experiment.candidateAllocationBasisPoints / 100}% · 最小样本 {experiment.minimumSampleSize} · {formatTime(experiment.updatedAt)}</Typography></Box><Stack direction="row" spacing={1}>{experiment.status === 'DRAFT' && <Button startIcon={<PlayArrowIcon />} onClick={() => void transition(experiment, 'RUNNING')}>启动</Button>}{experiment.status === 'RUNNING' && <Button onClick={() => void transition(experiment, 'PAUSED')}>暂停</Button>}{experiment.status === 'PAUSED' && <Button onClick={() => void transition(experiment, 'RUNNING')}>继续</Button>}{['RUNNING', 'PAUSED'].includes(experiment.status) && <Button color="success" onClick={() => void transition(experiment, 'COMPLETED')}>完成</Button>}</Stack></Stack></Paper>)}</Stack>;
}
