import { Box, Chip, Paper, Stack, Typography } from '@mui/material';

import type { TradeAutomationDetail } from './types';
import { SectionTitle, formatMoney, jsonList, statusColor, statusLabel } from './ui';

export function TradingExecutionDetail({ detail }: { detail: TradeAutomationDetail }) {
  return <Stack spacing={1.5}><SectionTitle title="执行审计详情" />
    {detail.decision && <Paper variant="outlined" sx={{ p: 2 }}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" spacing={1}><Box><Typography fontWeight={700}>{detail.decision.symbol} · {statusLabel(detail.decision.action)}</Typography><Typography variant="caption" color="text.secondary">{detail.estimatedTrades.length > 0 ? '不可执行产品已转为内部预估，不会调用交易所下单接口' : `建议 ${statusLabel(detail.decision.proposalStatus)}，由最终机器人、风控与 OMS 自动流转`}</Typography></Box><Chip label={`置信度 ${(Number(detail.decision.confidence) * 100).toFixed(0)}%`} /></Stack><Typography variant="body2" sx={{ mt: 1 }}>入场 {detail.decision.entryReference ?? '-'} · 目标 {detail.decision.targetPrice ?? '-'} · 失效 {detail.decision.invalidationPrice ?? '-'}</Typography>{jsonList(detail.decision.rationaleJson).map((reason) => <Typography key={reason} variant="body2" color="text.secondary">• {reason}</Typography>)}</Paper>}
    <Stack direction={{ xs: 'column', lg: 'row' }} spacing={1.5}>{detail.aiReviews.map((review) => <Paper key={review.reviewId} variant="outlined" sx={{ p: 2, flex: 1, minWidth: 0 }}><Stack direction="row" justifyContent="space-between"><Typography fontWeight={700}>{review.stage === 'DRAFT' ? '执行机器人初审' : '执行机器人反思终审'}</Typography><Chip size="small" color={statusColor(review.status)} label={statusLabel(review.status)} /></Stack><Typography variant="caption" color="text.secondary">{review.providerProfileId} / {review.modelName} / {review.reasoningEffort}</Typography><Typography component="pre" variant="body2" sx={{ mt: 1, whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', maxHeight: 260, overflow: 'auto' }}>{pretty(review.outputJson || review.errorMessage || '-')}</Typography></Paper>)}</Stack>
    {detail.estimatedTrades.map((projection) => <Paper key={projection.projectionId} variant="outlined" sx={{ p: 2, borderColor: 'info.light' }}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" spacing={1}><Box><Typography fontWeight={700}>{projection.exchange} · {projection.symbol} {statusLabel(projection.side)}</Typography><Typography variant="caption" color="text.secondary">预估编号 {projection.projectionId} · 风控 {projection.policyVersion}</Typography></Box><Chip size="small" color="info" label="仅预估，不会下单" /></Stack><Typography variant="body2" sx={{ mt: 1 }}>数量 {projection.quantity} · 合约单位 {projection.contractSize} · 名义价值 {formatMoney(projection.notionalUsdt)} · {projection.leverage}x · 预估保证金 {formatMoney(projection.initialMarginUsdt)}</Typography><Typography variant="body2">最新价 {projection.marketPrice} · 入场 {projection.entryReference} · 止盈 {projection.targetPrice} · 止损 {projection.stopPrice}</Typography><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2} sx={{ mt: 1 }}><Typography variant="body2" color="success.main">预估净盈利 {formatMoney(projection.estimatedProfitUsdt)}</Typography><Typography variant="body2" color="error.main">预估净亏损 {formatMoney(projection.estimatedLossUsdt)}</Typography><Typography variant="body2">盈亏比 {Number(projection.riskRewardRatio).toFixed(2)}</Typography></Stack><Typography variant="caption" color="text.secondary">费用已计入：入场 {formatMoney(projection.estimatedEntryCostUsdt)}，止盈退出 {formatMoney(projection.estimatedTargetExitCostUsdt)}，止损退出 {formatMoney(projection.estimatedStopExitCostUsdt)}。结果不代表真实成交或收益承诺。</Typography></Paper>)}
    {detail.riskAssessments.map((risk) => <Paper key={risk.assessmentId} variant="outlined" sx={{ p: 2 }}><Stack direction="row" justifyContent="space-between"><Typography fontWeight={700}>风控 · {risk.accountId}</Typography><Chip size="small" color={statusColor(risk.status)} label={statusLabel(risk.status)} /></Stack><Typography variant="body2">数量 {risk.quantity ?? '-'} · 名义价值 {formatMoney(risk.notionalUsdt)} · 保证金 {formatMoney(risk.initialMarginUsdt)} · 杠杆 {risk.leverage ?? '-'}x · 最大损失 {formatMoney(risk.estimatedMaximumLossUsdt)}</Typography>{jsonList(risk.reasonsJson).map((reason) => <Typography key={reason} variant="caption" color="text.secondary" display="block">{reason}</Typography>)}</Paper>)}
    {detail.orders.map((order) => <Paper key={order.orderId} variant="outlined" sx={{ p: 2 }}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" spacing={1}><Box><Typography fontWeight={700}>{order.exchange} {order.environment} · {order.symbol} {statusLabel(order.side)}</Typography><Typography variant="caption" color="text.secondary">{order.orderId} · client {order.clientOrderId || '-'}</Typography></Box><Chip size="small" color={statusColor(order.status)} label={statusLabel(order.status)} /></Stack><Typography variant="body2" sx={{ mt: 1 }}>请求 {order.requestedQuantity} · 成交 {order.filledQuantity} · 均价 {order.averageFillPrice ?? '-'} · {order.leverage}x</Typography>{order.submissionAttempts.map((attempt) => <Typography key={attempt.attemptId} variant="caption" display="block" color={attempt.status === 'REJECTED' ? 'error.main' : 'text.secondary'}>提交 #{attempt.attemptNumber} {statusLabel(attempt.status)} · HTTP {attempt.httpStatus ?? '-'} · {attempt.errorMessage || attempt.exchangeOrderId || '-'}</Typography>)}</Paper>)}
  </Stack>;
}

function pretty(value: string): string { try { return JSON.stringify(JSON.parse(value), null, 2); } catch { return value; } }
