import { Box, Paper, Stack, Typography } from '@mui/material';

import type { TradeAutomationDetail } from './types';
import { SectionTitle, StatusBadge, CopyableText, formatMoney, jsonList, statusLabel } from './ui';

export function TradingExecutionDetail({ detail }: { detail: TradeAutomationDetail }) {
  return <Stack spacing={1.75}><SectionTitle title="执行审计详情" subtitle="AI 终审反思、确定性风控评估与交易所提交记录" />
    {detail.decision && <Paper variant="outlined" sx={{ p: 2.25, boxShadow: '0 1px 3px rgba(15, 23, 42, 0.04)' }}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" spacing={1}><Box><Typography fontWeight={750} variant="body1">{detail.decision.symbol} · {statusLabel(detail.decision.action)}</Typography><Typography variant="caption" color="text.secondary">{detail.estimatedTrades.length > 0 ? '不可执行产品已转为内部预估，不会调用交易所下单接口' : `建议 ${statusLabel(detail.decision.proposalStatus)}，由最终机器人、风控与 OMS 自动流转`}</Typography></Box><StatusBadge status="INFO" label={`置信度 ${(Number(detail.decision.confidence) * 100).toFixed(0)}%`} /></Stack><Typography variant="body2" sx={{ mt: 1, fontVariantNumeric: 'tabular-nums' }}>入场 {detail.decision.entryReference ?? '-'} · 目标 {detail.decision.targetPrice ?? '-'} · 失效 {detail.decision.invalidationPrice ?? '-'}</Typography>{jsonList(detail.decision.rationaleJson).map((reason) => <Typography key={reason} variant="body2" color="text.secondary" sx={{ mt: 0.25 }}>• {reason}</Typography>)}</Paper>}
    <Stack direction={{ xs: 'column', lg: 'row' }} spacing={1.5}>{detail.aiReviews.map((review) => <Paper key={review.reviewId} variant="outlined" sx={{ p: 2, flex: 1, minWidth: 0, boxShadow: '0 1px 3px rgba(15, 23, 42, 0.04)' }}><Stack direction="row" justifyContent="space-between" alignItems="center"><Typography fontWeight={700}>{review.stage === 'DRAFT' ? '执行机器人初审' : '执行机器人反思终审'}</Typography><StatusBadge status={review.status} /></Stack><Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 0.25 }}>{review.providerProfileId} / {review.modelName} / {review.reasoningEffort}</Typography><Typography component="pre" variant="body2" sx={{ mt: 1.25, p: 1.25, bgcolor: 'action.hover', borderRadius: '4px', border: '1px solid', borderColor: 'divider', whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', maxHeight: 260, overflow: 'auto', fontFamily: 'monospace', fontSize: 12 }}>{pretty(review.outputJson || review.errorMessage || '-')}</Typography></Paper>)}</Stack>
    {detail.estimatedTrades.map((projection) => <Paper key={projection.projectionId} variant="outlined" sx={{ p: 2.25, borderColor: 'primary.light', bgcolor: 'rgba(29, 78, 216, 0.015)' }}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" spacing={1}><Box><Typography fontWeight={750}>{projection.exchange} · {projection.symbol} {statusLabel(projection.side)}</Typography><Stack direction="row" spacing={1} alignItems="center" sx={{ mt: 0.25 }}><Typography variant="caption" color="text.secondary">预估编号</Typography><CopyableText text={projection.projectionId} display={projection.projectionId.slice(0, 16) + '...'} /><Typography variant="caption" color="text.secondary">· 风控 {projection.policyVersion}</Typography></Stack></Box><StatusBadge status="ESTIMATED" label="仅预估，不会下单" /></Stack><Typography variant="body2" sx={{ mt: 1, fontVariantNumeric: 'tabular-nums' }}>数量 {projection.quantity} · 合约单位 {projection.contractSize} · 名义价值 {formatMoney(projection.notionalUsdt)} · {projection.leverage}x · 预估保证金 {formatMoney(projection.initialMarginUsdt)}</Typography><Typography variant="body2" sx={{ fontVariantNumeric: 'tabular-nums' }}>最新价 {projection.marketPrice} · 入场 {projection.entryReference} · 止盈 {projection.targetPrice} · 止损 {projection.stopPrice}</Typography><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2} sx={{ mt: 1 }}><Typography variant="body2" color="success.main" fontWeight={650}>预估净盈利 {formatMoney(projection.estimatedProfitUsdt)}</Typography><Typography variant="body2" color="error.main" fontWeight={650}>预估净亏损 {formatMoney(projection.estimatedLossUsdt)}</Typography><Typography variant="body2" fontWeight={650}>盈亏比 {Number(projection.riskRewardRatio).toFixed(2)}</Typography></Stack><Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 0.5 }}>费用已计入：入场 {formatMoney(projection.estimatedEntryCostUsdt)}，止盈退出 {formatMoney(projection.estimatedTargetExitCostUsdt)}，止损退出 {formatMoney(projection.estimatedStopExitCostUsdt)}。结果不代表真实成交或收益承诺。</Typography></Paper>)}
    {detail.riskAssessments.map((risk) => <Paper key={risk.assessmentId} variant="outlined" sx={{ p: 2 }}><Stack direction="row" justifyContent="space-between" alignItems="center"><Typography fontWeight={700}>风控 · {risk.accountId}</Typography><StatusBadge status={risk.status} /></Stack><Typography variant="body2" sx={{ mt: 0.5, fontVariantNumeric: 'tabular-nums' }}>数量 {risk.quantity ?? '-'} · 名义价值 {formatMoney(risk.notionalUsdt)} · 保证金 {formatMoney(risk.initialMarginUsdt)} · 杠杆 {risk.leverage ?? '-'}x · 最大损失 {formatMoney(risk.estimatedMaximumLossUsdt)}</Typography>{jsonList(risk.reasonsJson).map((reason) => <Typography key={reason} variant="caption" color="text.secondary" display="block">• {reason}</Typography>)}</Paper>)}
    {detail.orders.map((order) => <Paper key={order.orderId} variant="outlined" sx={{ p: 2 }}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" spacing={1}><Box><Typography fontWeight={750}>{order.exchange} {order.environment} · {order.symbol} {statusLabel(order.side)}</Typography><Stack direction="row" spacing={1} alignItems="center" sx={{ mt: 0.25 }}><CopyableText text={order.orderId} display={order.orderId.slice(0, 16) + '...'} /><Typography variant="caption" color="text.secondary">· client {order.clientOrderId || '-'}</Typography></Stack></Box><StatusBadge status={order.status} /></Stack><Typography variant="body2" sx={{ mt: 1, fontVariantNumeric: 'tabular-nums' }}>请求 {order.requestedQuantity} · 成交 {order.filledQuantity} · 均价 {order.averageFillPrice ?? '-'} · {order.leverage}x</Typography>{order.submissionAttempts.map((attempt) => <Typography key={attempt.attemptId} variant="caption" display="block" color={attempt.status === 'REJECTED' ? 'error.main' : 'text.secondary'} sx={{ mt: 0.35 }}>提交 #{attempt.attemptNumber} {statusLabel(attempt.status)} · HTTP {attempt.httpStatus ?? '-'} · {attempt.errorMessage || attempt.exchangeOrderId || '-'}</Typography>)}</Paper>)}
  </Stack>;
}

function pretty(value: string): string { try { return JSON.stringify(JSON.parse(value), null, 2); } catch { return value; } }
