apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - routes.yaml
images:
  - name: ghcr.io/example/finbot-backend
    newName: docker.io/speedproxy/finbot-backend
    newTag: latest
  - name: ghcr.io/example/finbot-quant
    newName: docker.io/speedproxy/finbot-quant
    newTag: latest
  - name: ghcr.io/example/finbot-web
    newName: docker.io/speedproxy/finbot-web
    newTag: latest
  - name: ghcr.io/example/finbot-proxy
    newName: docker.io/speedproxy/finbot-proxy
    newTag: latest
  - name: ghcr.io/example/finbot-browser-worker
    newName: docker.io/speedproxy/finbot-browser-worker
    newTag: latest
