--liquibase formatted sql

--changeset codex:046-multi-domain-source-catalog-v3 splitStatements:true endDelimiter:;
UPDATE information_source
SET provider = 'gate',
    category = 'exchange_announcements',
    version = version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE source_id = 'source_gate_announcements'
  AND source_mode = 'HTML_DOCUMENT'
  AND provider = 'first_party_html'
  AND deleted_at IS NULL;

UPDATE information_source
SET source_mode = 'SEARCH_DISCOVERY',
    provider = 'searxng_internal',
    endpoint_base_url = 'http://finbot-searxng:8080/search?categories=news&language=en&engines=google%20news%2Cbing%20news%2Cduckduckgo%20news%2Cbrave.news%2Cqwant%20news%2Cstartpage%20news%2Cyahoo%20news',
    credential_env = NULL,
    proxy_route_type = 'PUBLIC_DATA',
    maximum_results = 15,
    maximum_scrape_targets = 0,
    enabled = TRUE,
    version = version + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE source_id IN ('source_reuters_search', 'source_ap_search')
  AND source_mode = 'SEARCH_DISCOVERY'
  AND deleted_at IS NULL;

INSERT INTO information_source (
    source_id, display_name, source_mode, source_tier, category, provider,
    trust_weight, poll_interval_seconds, priority, asset_scope, feed_urls,
    seed_urls, search_queries, endpoint_base_url, credential_env,
    proxy_route_type, maximum_results, maximum_scrape_targets, enabled
) VALUES
    ('source_cisa_advisories', 'CISA 网络安全公告', 'RSS', 'T1', 'technology_cybersecurity', 'cisa',
     0.98, 1800, 'P0', '[]',
     '["https://www.cisa.gov/cybersecurity-advisories/all.xml"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 30, 0, TRUE),
    ('source_nvd_cves', 'NIST NVD 最新漏洞', 'JSON_API', 'T1', 'technology_vulnerabilities', 'nist_nvd',
     0.98, 3600, 'P1', '[]', '[]', '[]', '[]',
     'https://services.nvd.nist.gov/rest/json/cves/2.0?resultsPerPage=20',
     NULL, 'PUBLIC_DATA', 1, 0, TRUE),
    ('source_arxiv_ai', 'arXiv 人工智能研究', 'RSS', 'T2', 'technology_ai_research', 'arxiv',
     0.88, 21600, 'P2', '[]',
     '["https://rss.arxiv.org/rss/cs.AI","https://rss.arxiv.org/rss/cs.LG"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 40, 0, TRUE),
    ('source_github_security', 'GitHub Security 动态', 'RSS', 'T2', 'technology_security_ecosystem', 'github',
     0.90, 3600, 'P2', '[]',
     '["https://github.blog/security/feed/"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 20, 0, TRUE),
    ('source_who_news', 'WHO 全球卫生新闻', 'RSS', 'T1', 'healthcare_public_health', 'who',
     0.97, 3600, 'P1', '[]',
     '["https://www.who.int/rss-feeds/news-english.xml"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 25, 0, TRUE),
    ('source_fda_safety', 'FDA 医疗与食品安全', 'RSS', 'T1', 'healthcare_regulatory', 'fda',
     0.98, 1800, 'P0', '[]',
     '["https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/press-releases/rss.xml",
       "https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/fda-outbreaks/rss.xml",
       "https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/medwatch/rss.xml",
       "https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/recalls/rss.xml"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 40, 0, TRUE),
    ('source_usda_ars', 'USDA 农业科研动态', 'RSS', 'T1', 'agriculture_research', 'usda_ars',
     0.95, 21600, 'P1', '[]',
     '["https://www.ars.usda.gov/rss/?productName=Research+News"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 25, 0, TRUE),
    ('source_usda_wasde', 'USDA WASDE 供需报告', 'HTML_DOCUMENT', 'T1', 'agriculture_supply_demand', 'usda_wasde',
     0.99, 21600, 'P0', '[]', '[]',
     '["https://www.usda.gov/about-usda/general-information/staff-offices/office-chief-economist/commodity-markets/wasde-report"]',
     '[]', NULL, NULL, 'WEB_CRAWL', 5, 1, TRUE),
    ('source_noaa_nhc', 'NOAA 大西洋气旋预警', 'RSS', 'T1', 'climate_weather_risk', 'noaa_nhc',
     0.97, 1800, 'P1', '[]',
     '["https://www.nhc.noaa.gov/index-at.xml"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 25, 0, TRUE),
    ('source_usgs_earthquakes', 'USGS 重大地震监测', 'JSON_API', 'T1', 'geophysical_risk', 'usgs',
     0.98, 900, 'P1', '[]', '[]', '[]', '[]',
     'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_week.geojson',
     NULL, 'PUBLIC_DATA', 1, 0, TRUE),
    ('source_nasa_news', 'NASA 科学与航天动态', 'RSS', 'T1', 'science_space', 'nasa',
     0.95, 3600, 'P2', '[]',
     '["https://www.nasa.gov/news-release/feed/"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 20, 0, TRUE),
    ('source_federal_register', '美国 Federal Register', 'JSON_API', 'T1', 'cross_industry_regulation', 'federal_register',
     0.98, 1800, 'P0', '[]', '[]', '[]', '[]',
     'https://www.federalregister.gov/api/v1/documents.json?per_page=20&order=newest',
     NULL, 'PUBLIC_DATA', 1, 0, TRUE),
    ('source_bbc_news', 'BBC 综合新闻', 'RSS', 'T2', 'broad_news', 'bbc',
     0.90, 900, 'P1', '[]',
     '["https://feeds.bbci.co.uk/news/world/rss.xml",
       "https://feeds.bbci.co.uk/news/business/rss.xml",
       "https://feeds.bbci.co.uk/news/technology/rss.xml",
       "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
       "https://feeds.bbci.co.uk/news/health/rss.xml"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 50, 0, TRUE),
    ('source_npr_news', 'NPR 综合新闻', 'RSS', 'T2', 'broad_news', 'npr',
     0.88, 1800, 'P2', '[]',
     '["https://feeds.npr.org/1001/rss.xml",
       "https://feeds.npr.org/1006/rss.xml",
       "https://feeds.npr.org/1007/rss.xml"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 40, 0, TRUE),
    ('source_aljazeera_news', 'Al Jazeera 全球新闻', 'RSS', 'T2', 'broad_news', 'aljazeera',
     0.85, 900, 'P1', '[]',
     '["https://www.aljazeera.com/xml/rss/all.xml"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 30, 0, TRUE),
    ('source_dw_news', 'DW 全球新闻', 'RSS', 'T2', 'broad_news', 'dw',
     0.85, 1800, 'P2', '[]',
     '["https://rss.dw.com/rdf/rss-en-all"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 30, 0, TRUE),
    ('source_guardian_news', 'The Guardian 综合新闻', 'RSS', 'T2', 'broad_news', 'guardian',
     0.88, 900, 'P1', '[]',
     '["https://www.theguardian.com/world/rss",
       "https://www.theguardian.com/business/rss",
       "https://www.theguardian.com/technology/rss",
       "https://www.theguardian.com/science/rss",
       "https://www.theguardian.com/environment/rss",
       "https://www.theguardian.com/global-development/rss"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 60, 0, TRUE),
    ('source_nyt_news', 'The New York Times 综合新闻', 'RSS', 'T2', 'broad_news', 'new_york_times',
     0.90, 900, 'P1', '[]',
     '["https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
       "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml",
       "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",
       "https://rss.nytimes.com/services/xml/rss/nyt/Science.xml",
       "https://rss.nytimes.com/services/xml/rss/nyt/Health.xml",
       "https://rss.nytimes.com/services/xml/rss/nyt/Climate.xml"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 60, 0, TRUE),
    ('source_france24_news', 'France 24 全球新闻', 'RSS', 'T2', 'broad_news', 'france24',
     0.85, 900, 'P2', '[]',
     '["https://www.france24.com/en/rss"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 30, 0, TRUE),
    ('source_cbs_news', 'CBS News 综合新闻', 'RSS', 'T2', 'broad_news', 'cbs_news',
     0.86, 900, 'P2', '[]',
     '["https://www.cbsnews.com/latest/rss/main"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 30, 0, TRUE),
    ('source_cnbc_news', 'CNBC 财经新闻', 'RSS', 'T2', 'finance_news', 'cnbc',
     0.90, 600, 'P1', '[]',
     '["https://www.cnbc.com/id/100003114/device/rss/rss.html"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 30, 0, TRUE),
    ('source_marketwatch_news', 'MarketWatch 市场新闻', 'RSS', 'T2', 'finance_news', 'marketwatch',
     0.86, 600, 'P1', '[]',
     '["https://feeds.marketwatch.com/marketwatch/topstories/"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 30, 0, TRUE),
    ('source_coindesk_news', 'CoinDesk 加密行业新闻', 'RSS', 'T2', 'crypto_news', 'coindesk',
     0.84, 600, 'P1', '["BTCUSDT","ETHUSDT","SOLUSDT"]',
     '["https://www.coindesk.com/arc/outboundfeeds/rss/"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 30, 0, TRUE),
    ('source_scmp_news', 'SCMP 亚洲新闻', 'RSS', 'T2', 'asia_news', 'scmp',
     0.84, 900, 'P2', '[]',
     '["https://www.scmp.com/rss/91/feed"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 30, 0, TRUE),
    ('source_chinanews_cn', '中国新闻网滚动新闻', 'RSS', 'T2', 'cn_broad_news', 'chinanews',
     0.88, 600, 'P1', '[]',
     '["https://www.chinanews.com.cn/rss/scroll-news.xml"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 40, 0, TRUE),
    ('source_people_cn', '人民网政经新闻', 'RSS', 'T2', 'cn_policy_finance_news', 'people_cn',
     0.90, 900, 'P1', '[]',
     '["http://www.people.com.cn/rss/politics.xml","http://www.people.com.cn/rss/finance.xml"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 40, 0, TRUE),
    ('source_sina_cn', '新浪滚动新闻', 'RSS', 'T3', 'cn_broad_news', 'sina',
     0.76, 600, 'P2', '[]',
     '["https://rss.sina.com.cn/news/marquee/ddt.xml"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 30, 0, TRUE),
    ('source_ifeng_cn', '凤凰网综合新闻', 'RSS', 'T3', 'cn_broad_news', 'ifeng',
     0.78, 900, 'P2', '[]',
     '["https://news.ifeng.com/rss/index.xml"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 30, 0, TRUE),
    ('source_36kr_cn', '36Kr 科技与创投', 'RSS', 'T3', 'cn_technology_finance_news', '36kr',
     0.80, 900, 'P2', '[]',
     '["https://36kr.com/feed"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 30, 0, TRUE),
    ('source_ithome_cn', 'IT之家科技新闻', 'RSS', 'T3', 'cn_technology_news', 'ithome',
     0.78, 900, 'P2', '[]',
     '["https://www.ithome.com/rss/"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 30, 0, TRUE),
    ('source_oschina_cn', '开源中国技术新闻', 'RSS', 'T3', 'cn_technology_open_source', 'oschina',
     0.78, 1800, 'P2', '[]',
     '["https://www.oschina.net/news/rss"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 30, 0, TRUE),
    ('source_sspai_cn', '少数派科技动态', 'RSS', 'T3', 'cn_technology_news', 'sspai',
     0.76, 1800, 'P3', '[]',
     '["https://sspai.com/feed"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 25, 0, TRUE),
    ('source_cnbeta_cn', 'cnBeta 科技新闻', 'RSS', 'T3', 'cn_technology_news', 'cnbeta',
     0.74, 900, 'P3', '[]',
     '["https://www.cnbeta.com.tw/backend.php"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 30, 0, TRUE),
    ('source_searxng_global_search', 'SearXNG 国际多引擎搜索', 'SEARCH_DISCOVERY', 'T4', 'search_discovery', 'searxng_internal',
     0.55, 1800, 'P2', '[]', '[]', '[]',
     '["technology finance agriculture healthcare energy regulation latest developments"]',
     'http://finbot-searxng:8080/search?categories=general&language=auto&engines=google%2Cbing%2Cduckduckgo%2Cbrave%2Cqwant%2Cstartpage%2Cyahoo',
     NULL, 'PUBLIC_DATA', 20, 0, TRUE),
    ('source_searxng_news_search', 'SearXNG 国际新闻多引擎', 'SEARCH_DISCOVERY', 'T4', 'broad_news_discovery', 'searxng_internal',
     0.55, 900, 'P2', '[]', '[]', '[]',
     '["world business technology health science climate latest news"]',
     'http://finbot-searxng:8080/search?categories=news&language=en&engines=google%20news%2Cbing%20news%2Cduckduckgo%20news%2Cbrave.news%2Cqwant%20news%2Cstartpage%20news%2Cyahoo%20news',
     NULL, 'PUBLIC_DATA', 20, 0, TRUE),
    ('source_searxng_cn_mainstream', 'SearXNG 国内主流新闻定向搜索', 'SEARCH_DISCOVERY', 'T4', 'cn_broad_news_discovery', 'searxng_internal',
     0.55, 900, 'P2', '[]', '[]', '[]',
     '["(site:news.cn OR site:cctv.com OR site:people.com.cn OR site:chinanews.com.cn OR site:thepaper.cn) 最新 重要 新闻"]',
     'http://finbot-searxng:8080/search?categories=general%2Cnews&language=zh-CN&engines=baidu%2C360search%2Csogou%2Csogou%20wechat',
     NULL, 'PUBLIC_DATA', 20, 0, TRUE),
    ('source_searxng_cn_finance', 'SearXNG 国内财经科技定向搜索', 'SEARCH_DISCOVERY', 'T4', 'cn_finance_technology_discovery', 'searxng_internal',
     0.55, 900, 'P2', '[]', '[]', '[]',
     '["(site:cls.cn OR site:yicai.com OR site:stcn.com OR site:cnstock.com OR site:caixin.com OR site:36kr.com) 最新 财经 科技 市场"]',
     'http://finbot-searxng:8080/search?categories=general%2Cnews&language=zh-CN&engines=baidu%2C360search%2Csogou%2Csogou%20wechat',
     NULL, 'PUBLIC_DATA', 20, 0, TRUE),
    ('source_binance_announcements', 'Binance 公告与 API 变更', 'HTML_DOCUMENT', 'T1', 'exchange_announcements', 'binance',
     0.94, 900, 'P1', '["BTCUSDT","ETHUSDT","BNBUSDT"]', '[]',
     '["https://www.binance.com/en/support/announcement",
       "https://developers.binance.com/docs/binance-spot-api-docs"]',
     '[]', NULL, NULL, 'WEB_CRAWL', 10, 2, TRUE),
    ('source_okx_announcements', 'OKX 公告与 API 变更', 'HTML_DOCUMENT', 'T1', 'exchange_announcements', 'okx',
     0.94, 900, 'P1', '["BTCUSDT","ETHUSDT","SOLUSDT"]', '[]',
     '["https://www.okx.com/help/section/announcements-latest-announcements",
       "https://www.okx.com/docs-v5/log_en/"]',
     '[]', NULL, NULL, 'WEB_CRAWL', 10, 2, TRUE),
    ('source_coinbase_news', 'Coinbase 官方新闻', 'HTML_DOCUMENT', 'T1', 'exchange_announcements', 'coinbase',
     0.94, 1800, 'P1', '["BTCUSD","ETHUSD","BTCUSDT","ETHUSDT"]', '[]',
     '["https://www.coinbase.com/blog/landing"]',
     '[]', NULL, NULL, 'WEB_CRAWL', 10, 1, TRUE),
    ('source_bitget_announcements', 'Bitget 公告 API', 'JSON_API', 'T1', 'exchange_announcements', 'bitget',
     0.95, 900, 'P1', '["BTCUSDT","ETHUSDT","SOLUSDT"]', '[]', '[]', '[]',
     'https://api.bitget.com/api/v2/public/annoucements?language=en_US',
     NULL, 'PUBLIC_DATA', 1, 0, TRUE),
    ('source_kucoin_announcements', 'KuCoin 公告 API', 'JSON_API', 'T1', 'exchange_announcements', 'kucoin',
     0.95, 900, 'P1', '["BTCUSDT","ETHUSDT","SOLUSDT"]', '[]', '[]', '[]',
     'https://api.kucoin.com/api/ua/v1/market/announcement?lang=en_US',
     NULL, 'PUBLIC_DATA', 1, 0, TRUE),
    ('source_kraken_news', 'Kraken 官方新闻', 'RSS', 'T1', 'exchange_announcements', 'kraken',
     0.94, 1800, 'P1', '["BTCUSD","ETHUSD","BTCUSDT","ETHUSDT"]',
     '["https://blog.kraken.com/feed/"]',
     '[]', '[]', NULL, NULL, 'PUBLIC_DATA', 25, 0, TRUE),
    ('source_ai_grok_web_search', 'Grok 行业 Web Search', 'AI_WEB_SEARCH', 'T3', 'cross_industry_ai_discovery', 'ai_web_search',
     0.68, 3600, 'P2', '[]', '[]', '[]',
     '["科技 金融 农业 医疗 能源领域最新重要事件及其原始出处"]',
     NULL, NULL, NULL, 15, 0, FALSE),
    ('source_ai_gemini_web_search', 'Gemini 行业 Web Search', 'AI_WEB_SEARCH', 'T3', 'cross_industry_ai_discovery', 'ai_web_search',
     0.68, 3600, 'P2', '[]', '[]', '[]',
     '["科技 金融 农业 医疗 能源领域最新重要事件及其原始出处"]',
     NULL, NULL, NULL, 15, 0, FALSE)
ON CONFLICT (source_id) DO NOTHING;

INSERT INTO information_source_ai_web_search (
    source_id, provider_profile_id, model_name, reasoning_effort, tool_type
) SELECT 'source_ai_grok_web_search', 'provider_grok_sub2api', 'grok-4.5', 'XHIGH', 'WEB_SEARCH'
WHERE EXISTS (
    SELECT 1 FROM information_source WHERE source_id = 'source_ai_grok_web_search'
)
ON CONFLICT (source_id) DO NOTHING;

INSERT INTO information_source_ai_web_search (
    source_id, provider_profile_id, model_name, reasoning_effort, tool_type
) SELECT 'source_ai_gemini_web_search', 'provider_gemini_default', 'gemini-3.5-flash', 'MAX', 'GOOGLE_SEARCH'
WHERE EXISTS (
    SELECT 1 FROM information_source WHERE source_id = 'source_ai_gemini_web_search'
)
ON CONFLICT (source_id) DO NOTHING;

INSERT INTO information_source_catalog_manifest (
    catalog_id, catalog_version, manifest_hash, source_count, source_ids
) VALUES (
    'catalog_default_sources',
    'v3',
    'e1abe028cf7e97ac51b40b2485a37a4bbcf48d969ad31143b379bcf537abed22',
    61,
    '["source_36kr_cn","source_ai_gemini_web_search","source_ai_grok_web_search",
      "source_aljazeera_news","source_ap_search","source_arxiv_ai","source_bbc_news","source_binance_announcements",
      "source_bitget_announcements","source_bls_labor","source_bybit_announcements",
      "source_cbs_news","source_cftc_cot","source_chinanews_cn","source_cisa_advisories","source_cnbc_news",
      "source_cnbeta_cn","source_coinbase_news","source_coindesk_news","source_dw_news","source_ecb_official",
      "source_eia_weekly","source_fda_safety","source_federal_register","source_federal_reserve",
      "source_france24_news","source_fred_macro","source_gate_announcements",
      "source_github_security","source_global_search","source_guardian_news",
      "source_ifeng_cn","source_ithome_cn","source_kraken_news","source_kucoin_announcements","source_marketwatch_news",
      "source_nasa_news","source_noaa_nhc","source_npr_news","source_nvd_cves",
      "source_nyt_news","source_okx_announcements","source_opec_news","source_oschina_cn",
      "source_people_cn","source_reuters_search",
      "source_scmp_news","source_searxng_cn_finance","source_searxng_cn_mainstream",
      "source_searxng_global_search","source_searxng_news_search","source_sec_edgar",
      "source_sina_cn","source_sspai_cn","source_usda_ars","source_usda_wasde",
      "source_usgs_earthquakes","source_white_house","source_who_news",
      "source_world_bank_macro","source_x_market_search"]'::jsonb
);

--rollback DELETE FROM information_source_catalog_manifest WHERE catalog_id = 'catalog_default_sources' AND catalog_version = 'v3';
--rollback UPDATE information_source SET endpoint_base_url = NULL, provider = CASE source_id WHEN 'source_reuters_search' THEN 'reuters' ELSE 'ap' END, proxy_route_type = 'WEB_CRAWL', enabled = FALSE, version = version + 1, updated_at = CURRENT_TIMESTAMP WHERE source_id IN ('source_reuters_search','source_ap_search') AND provider = 'searxng_internal';
--rollback UPDATE information_source SET provider = 'first_party_html', version = version + 1, updated_at = CURRENT_TIMESTAMP WHERE source_id = 'source_gate_announcements' AND provider = 'gate';
--rollback UPDATE information_source SET enabled = FALSE, deleted_at = COALESCE(deleted_at, CURRENT_TIMESTAMP), version = version + 1, updated_at = CURRENT_TIMESTAMP WHERE source_id IN ('source_36kr_cn','source_ai_gemini_web_search','source_ai_grok_web_search','source_aljazeera_news','source_arxiv_ai','source_bbc_news','source_binance_announcements','source_bitget_announcements','source_cbs_news','source_chinanews_cn','source_cisa_advisories','source_cnbc_news','source_cnbeta_cn','source_coindesk_news','source_coinbase_news','source_dw_news','source_fda_safety','source_federal_register','source_france24_news','source_github_security','source_guardian_news','source_ifeng_cn','source_ithome_cn','source_kraken_news','source_kucoin_announcements','source_marketwatch_news','source_nasa_news','source_noaa_nhc','source_npr_news','source_nvd_cves','source_nyt_news','source_okx_announcements','source_oschina_cn','source_people_cn','source_scmp_news','source_searxng_cn_finance','source_searxng_cn_mainstream','source_searxng_global_search','source_searxng_news_search','source_sina_cn','source_sspai_cn','source_usda_ars','source_usda_wasde','source_usgs_earthquakes','source_who_news');
